s = set()

# n = int(input("Enter no.:"))
# s.add(int(n))
# n = int(input("Enter no.:"))
# s.add(int(n))
# n = int(input("Enter no.:"))
# s.add(int(n))
# n = int(input("Enter no.:"))
# s.add(int(n))
# n = int(input("Enter no.:"))
# s.add(int(n))
# n = int(input("Enter no.:"))
# s.add(int(n))
# n = int(input("Enter no.:"))
# s.add(int(n))
# n = int(input("Enter no.:"))
# s.add(int(n))
# print(s)
